INTDIR=$(X64DIR)/interrupts
INTDIR_FULL=$(X64DIR_FULL)/interrupts

ARCHOBJECTS += $(INTDIR)/interrupt_functions.o $(INTDIR)/interrupt_api.o $(INTDIR)/interrupt_controller.o $(INTDIR)/pic.o $(INTDIR)/apic.o $(INTDIR)/controller.o